### ISSUE TITLE
Migrate Document attributes reference documentation to YAML structure

### ISSUE THREAD

**Issue by kickoke** [metanorma/metanorma.org#441]
Hi Nick, 
As we've agreed in our meeting today, you will take care of the migration of the Document Attributes reference documents from AsciiDoc into YAML. In terms of flavors, I would focus on migrating flavors that are in heavy use first, and then migrate other flavors once it makes sense from a strategic standpoint. Should you need assistance in terms of tech writing or a review, just drop me a line. 

**Deadlines**: It would be great if you can populate all YAML files within the next week. (Step 1)
For Step 2: Quality matters more than time, but it would be great, if you could complete this step until July 11. 

The next steps would be to place the files into the directories they belong and write a script for the website, that compiles the reference. 

The process we agreed on looks like this:
1. First iteration: Populate the YAML files with a self-written script that fills: Tags, Title, Description. 
2. Refine the entries by adding more information for each attribute. If a document attribute doesn't have a value for a key, it either stays empty (for example `more information` or  `example`) or get assigned a default value (for example `required: false`)

You can find the empty YAML files in this directory:
https://github.com/metanorma/metanorma.org/tree/staging/reference_docs/YAML_models

Tip: The standoc_document_attributes.yaml file contains a how-to on using the YAML model and all keys.

The existing reference documentation files:
- Standoc: https://github.com/metanorma/metanorma.org/blob/master/author/ref/document-attributes.adoc
- ISO: https://github.com/metanorma/metanorma.org/blob/master/author/iso/ref/document-attributes.adoc
- IEC: https://github.com/metanorma/metanorma.org/blob/master/author/iec/ref/document-attributes.adoc
- OGC: https://github.com/metanorma/metanorma.org/blob/master/author/ogc/authoring.adoc
- IETF v2: https://github.com/metanorma/metanorma.org/blob/master/author/ietf/ref/document-attributes-v2.adoc
- IETF v3: https://github.com/metanorma/metanorma.org/blob/master/author/ietf/ref/document-attributes.adoc
- CalConnect: https://github.com/metanorma/metanorma.org/blob/master/author/cc/authoring.adoc

Thank you very much!

CC: @strogonoff @ronaldtse

**Comment by ronaldtse** [comment]
@opoudjis are you sure you have time for this? I'm sure @manuel489 would be equally be as happy to do this.

**Comment by ronaldtse** [comment]
@kickoke just a quick note that we don't usually use capitalised filenames/directory names because some platforms get capitalisation mixed up, and Git does not help with the letter case conversion. Let's always stick to lower case letters.

**Comment by ronaldtse** [comment]
@manuel489 could you help with this? Talked to @opoudjis already, there are some things he has to do in addition but basically you should be able to handle this. Thanks.

**Comment by ronaldtse** [comment]
I finally understand what's going on here. We're trying to set a unified data structure for documenting "document attributes".

Right now it looks like this:
https://github.com/metanorma/metanorma.org/blob/e6baeedcd61dc951fe645a909582360d15dfcab5/reference_docs/YAML_models/calconnect_document_attributes.yaml#L10-L13

i.e.
* name
* title
* description
* tags
* flavor (this is now done by the per-flavour grouping)

In addition, you may want to add:
* type of value accepted (enumerated values, text, structured information)
* default value (if any)
* if value type is an enumeration, the description of allowed values

**Comment by kickoke** [comment]
> In addition, you may want to add:
> 
> * mandatory or optional
> * type of value accepted (enumerated values, text, structured information)
> * default value (if any)
> * if value type is an enumeration, the description of allowed values

Yes, I've defined the complete document model in the standoc_document_attributes.yaml. There is also a How-To in there on using the defined document structure. 

The structure in the flavor only resembles Step 1, so this isn't how the finished docs should look like - it just makes the migration easier. :)

**Comment by ronaldtse** [comment]
@kickoke ahh! Glad you had the foresight for those keys. It just wasn't clear from the description above that these items were handled.

**Comment by opoudjis** [comment]
Ok, now that I'm actually getting around to this :-/

As I've negotiated with @kickoke,  the first four attributes are mandatory:

````
# nameOfTheAttribute: # Unique across document attributes for a flavor
#   tags: []  # A list of strings; Include flavor and type of attribute, e.g. "Author info"
#   title: "name of the attribute"
#   description: "Can contain inline and block AsciiDoc formatting".
````

For each of the following, populate only if they do not have the default value. I will then write a script to populate the default values.

````
#   required: true #Describes if the attribute is required to generate a well-formed doc or optional. Takes a boolean.
````

Default is false. ONLY populate if required is true, or "don't know" (in which case, I'll find out and populate it manually).

````
#   declaration: ":attribute:" #How the attribute is invoked
````

Default is `:{nameOfTheAttribute}:`. ONLY populate if it has a different value from that.

````
#   value_spec: "Comma-delimited list of classification tokens, expressed as `type:value` pairs. The `type:` prefix is optional, where omitted `default:` prefix is auto-supplied"
````

The possible values here are: text, number, comma-list, semicolon-list, or other (which you provide a full text description for). Default is text. ONLY populate if it has a different value from that.

````
#   value_default: null  #OPTIONAL A string showing literal value for this attribute, without quotes. If the attribute doesn't take a values, this stays empty.
````

Default is null. ONLY populate if a default value ends up supplied.

````
#   added_in_version: v1.9.1 # Could be auto-inferred, however the renderer might run into trouble, see https://github.com/metanorma/metanorma.org/wiki/Flavor-reference-structure-specification
````

Default is null. ONLY populate if an explicit value has been given for the version when the attribute was added. (We really do have to assume "from the beginning of time" otherwise.

````
#   example: >- ...  #OPTIONAL Should be pure AsciiDoc. Will be rendered as is inside an example block.
````

Only provide if you have one.

````
#   more_information: "string" #OPTIONAL Use to provide related links, such as a blog article that discusses background info, if applicable
````

Only provide if you have one.

**Comment by opoudjis** [comment]
Script:

````
require "yaml"
  
a = YAML.safe_load(File.read(ARGV.first))
a["document_attributes"].each_key do |x|
  a["document_attributes"][x]["required"] ||= false
  a["document_attributes"][x]["declaration"] ||= ":#{x}:"
  a["document_attributes"][x]["value_spec"] ||= "text"
  a["document_attributes"][x]["value_default"] ||= nil
  a["document_attributes"][x]["added_in_version"] ||= nil
end
print YAML.dump(a)
````

Input:

````
version: v1.x.x #@opoudjis Check versions throughout this doc. Huuuge thanks!
flavor: standoc

document_attributes:
#--- Build and validation ---#
  nodoc:
    tags: ["Build and validation"]
    title: No document generation #@opoudjis Review how we should actually name :nodoc:
    description: "TBD: Explain what 'nodoc' is used for."

  novalid:
    tags: ["Build and validation"]
    title: "document type"
    description: "TBD: Explain what “novalid” is used for."

#--- Bibliographic lookup ---#
  no-isobib:
    tags: ["Bibliographic lookup"]
    title: "name of the attribute"
    description: "Can contain inline and block AsciiDoc formatting."
````

Output:

````
---
version: v1.x.x
flavor: standoc
document_attributes:
  nodoc:
    tags:
    - Build and validation
    title: No document generation
    description: 'TBD: Explain what ''nodoc'' is used for.'
    required: false
    declaration: ":nodoc:"
    value_spec: text
    value_default:
    added_in_version:
  novalid:
    tags:
    - Build and validation
    title: document type
    description: 'TBD: Explain what “novalid” is used for.'
    required: false
    declaration: ":novalid:"
    value_spec: text
    value_default:
    added_in_version:
  no-isobib:
    tags:
    - Bibliographic lookup
    title: name of the attribute
    description: Can contain inline and block AsciiDoc formatting.
    required: false
    declaration: ":no-isobib:"
    value_spec: text
    value_default:
    added_in_version:
````
